export * from "./1_hero";
export * from "./2_advantages";
export * from "./3_about_security_specialist";
export * from "./4_course_for";
export * from "./5_salary_growing";
export * from "./6_course_program";
export * from "./7_main_course_program";
export * from "./layout";
export * from "./page";
